//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.24 at 10:20:15 AM CAT 
//


package za.co.mathmuncher.domain;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="anthropod" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="body" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="legs" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="type" type="{http://mathmuncher.co.za/ws/schemas/ex}exerciseType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "anthropod"
})
@XmlRootElement(name = "anthropodExerciseResponse")
public class AnthropodExerciseResponse {

    protected List<AnthropodExerciseResponse.Anthropod> anthropod;
    @XmlAttribute(name = "type", namespace = "http://mathmuncher.co.za/ws/schemas/ex")
    protected ExerciseType type;

    /**
     * Gets the value of the anthropod property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the anthropod property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAnthropod().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AnthropodExerciseResponse.Anthropod }
     * 
     * 
     */
    public List<AnthropodExerciseResponse.Anthropod> getAnthropod() {
        if (anthropod == null) {
            anthropod = new ArrayList<AnthropodExerciseResponse.Anthropod>();
        }
        return this.anthropod;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link ExerciseType }
     *     
     */
    public ExerciseType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExerciseType }
     *     
     */
    public void setType(ExerciseType value) {
        this.type = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="body" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="legs" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Anthropod {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "body", namespace = "http://mathmuncher.co.za/ws/schemas/ex", required = true)
        protected int body;
        @XmlAttribute(name = "legs", namespace = "http://mathmuncher.co.za/ws/schemas/ex", required = true)
        protected String legs;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the body property.
         * 
         */
        public int getBody() {
            return body;
        }

        /**
         * Sets the value of the body property.
         * 
         */
        public void setBody(int value) {
            this.body = value;
        }

        /**
         * Gets the value of the legs property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLegs() {
            return legs;
        }

        /**
         * Sets the value of the legs property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLegs(String value) {
            this.legs = value;
        }

    }

}
