//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.24 at 10:20:15 AM CAT 
//


package za.co.mathmuncher.domain;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for exerciseType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="exerciseType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="MULTIPLICATION"/>
 *     &lt;enumeration value="DIVISION"/>
 *     &lt;enumeration value="ADDITION"/>
 *     &lt;enumeration value="MINUS"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "exerciseType")
@XmlEnum
public enum ExerciseType {

    MULTIPLICATION,
    DIVISION,
    ADDITION,
    MINUS;

    public String value() {
        return name();
    }

    public static ExerciseType fromValue(String v) {
        return valueOf(v);
    }

}
