//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.24 at 10:20:15 AM CAT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://mathmuncher.co.za/ws/schemas/ex", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package za.co.mathmuncher.domain;
